import { db } from '@/db';
import { issues } from '@/db/schema';

async function main() {
    const sampleIssues = [
        // Roads - 8 issues (status: 4 received, 2 in_progress, 2 resolved)
        {
            userId: 5,
            title: 'Large pothole on Main Street near City Mall',
            description: 'There is a dangerous pothole approximately 2 feet wide and 6 inches deep on Main Street. It is causing traffic disruption and poses a safety hazard for vehicles, especially during night time.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5204,
            longitude: 73.8567,
            address: '123 Main Street, near City Mall',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 15,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            userId: 7,
            title: 'Damaged road surface near City Hospital',
            description: 'The road surface near the main entrance of City Hospital has multiple cracks and broken patches. This is causing inconvenience to ambulances and emergency vehicles accessing the hospital.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5312,
            longitude: 73.8445,
            address: 'Hospital Road, opposite City Hospital',
            status: 'in_progress',
            departmentId: 1,
            assignedBy: 1,
            adminNotes: 'Road repair work assigned to contractor. Expected completion in 5 days.',
            voteCount: 22,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 9,
            title: 'Traffic signal not working at Market Junction',
            description: 'The traffic signal at Market Junction has been malfunctioning for the past two days. All lights remain off causing traffic chaos during peak hours. Urgent attention required.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5156,
            longitude: 73.8623,
            address: 'Market Junction, MG Road',
            status: 'resolved',
            departmentId: 1,
            assignedBy: 2,
            adminNotes: 'Traffic signal repaired. New control unit installed. Issue resolved.',
            voteCount: 18,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 4,
            title: 'Road construction debris blocking pathway',
            description: 'Construction materials and debris from recent road work have been left on the pedestrian pathway. This is forcing pedestrians to walk on the main road, creating a safety hazard.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5423,
            longitude: 73.8734,
            address: '45 Station Road, near Railway Crossing',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 12,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 11,
            title: 'Broken speed breaker causing vehicle damage',
            description: 'The speed breaker near the school has broken edges and exposed metal rods. Several vehicles have reported tire damage. The broken pieces also pose danger to school children crossing the road.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5278,
            longitude: 73.8512,
            address: 'School Road, opposite St. Mary\'s High School',
            status: 'in_progress',
            departmentId: 1,
            assignedBy: 1,
            adminNotes: 'Speed breaker removal in progress. New one will be installed within 3 days.',
            voteCount: 25,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            userId: 6,
            title: 'Unmarked road divider at night causing accidents',
            description: 'The newly constructed road divider lacks reflective markers making it invisible at night. Multiple minor accidents have been reported at this location in the past week.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5389,
            longitude: 73.8656,
            address: 'NH-48 Highway, near Toll Plaza',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 8,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 8,
            title: 'Road cave-in after heavy rainfall',
            description: 'A section of the road approximately 10 feet long has caved in after last week\'s heavy rainfall. The area has been cordoned off but needs immediate repair to restore traffic flow.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5501,
            longitude: 73.8789,
            address: '89 River Road, near Bridge',
            status: 'resolved',
            departmentId: 1,
            assignedBy: 2,
            adminNotes: 'Emergency repair work completed. Road reinforced and resurfaced. Traffic restored.',
            voteCount: 20,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            userId: 10,
            title: 'Faded road markings causing confusion',
            description: 'The lane markings and zebra crossings on Park Avenue have completely faded. This is causing confusion among drivers and endangering pedestrians trying to cross the road.',
            category: 'Roads',
            imageUrl: null,
            latitude: 18.5245,
            longitude: 73.8478,
            address: 'Park Avenue, near Central Garden',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 14,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },

        // Sanitation - 6 issues (status: 2 received, 2 in_progress, 2 resolved)
        {
            userId: 3,
            title: 'Garbage not collected for 3 days in residential area',
            description: 'The municipal garbage collection has not happened in our residential area for the past three days. The accumulated waste is creating unhygienic conditions and foul smell. Stray dogs are scattering the garbage.',
            category: 'Sanitation',
            imageUrl: null,
            latitude: 18.5334,
            longitude: 73.8590,
            address: 'Green Valley Society, Sector 12',
            status: 'in_progress',
            departmentId: 2,
            assignedBy: 1,
            adminNotes: 'Collection vehicle breakdown issue. Backup vehicle assigned. Collection scheduled for tomorrow morning.',
            voteCount: 19,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 12,
            title: 'Overflowing dustbin on Park Road',
            description: 'The public dustbin near the park gate has been overflowing for days. Waste is spilling onto the footpath and the smell is unbearable. This is a health hazard especially with the park being used by children.',
            category: 'Sanitation',
            imageUrl: null,
            latitude: 18.5267,
            longitude: 73.8523,
            address: 'Park Road, near Rose Garden',
            status: 'resolved',
            departmentId: 2,
            assignedBy: 2,
            adminNotes: 'Dustbin emptied and area cleaned. Dustbin size increased and collection frequency updated to twice daily.',
            voteCount: 16,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            userId: 5,
            title: 'Street cleaning required on Market Street',
            description: 'Market Street has not been cleaned by municipal workers for over a week. There is accumulated litter, vegetable waste, and plastic bags all along the street. This is affecting business and causing health concerns.',
            category: 'Sanitation',
            imageUrl: null,
            latitude: 18.5178,
            longitude: 73.8601,
            address: 'Market Street, Commercial Area',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 11,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            userId: 9,
            title: 'Dead animal on roadside needs removal',
            description: 'A dead stray dog has been lying on the roadside near the bus stop for two days. The decomposing body is creating a severe health hazard and unbearable stench for commuters and nearby residents.',
            category: 'Sanitation',
            imageUrl: null,
            latitude: 18.5445,
            longitude: 73.8712,
            address: 'Bus Stop, near City Bus Depot',
            status: 'in_progress',
            departmentId: 2,
            assignedBy: 1,
            adminNotes: 'Sanitation team dispatched. Removal and sanitization work in progress.',
            voteCount: 21,
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            userId: 7,
            title: 'Public toilet in unhygienic condition',
            description: 'The public toilet near the railway station is in extremely poor condition. It has not been cleaned in weeks, water supply is erratic, and the drainage is blocked. Urgent maintenance is required.',
            category: 'Sanitation',
            imageUrl: null,
            latitude: 18.5512,
            longitude: 73.8823,
            address: 'Railway Station Road, near Platform 1',
            status: 'resolved',
            departmentId: 2,
            assignedBy: 2,
            adminNotes: 'Toilet thoroughly cleaned, drainage repaired, and water connection fixed. Daily cleaning schedule established.',
            voteCount: 17,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            userId: 4,
            title: 'Blocked drainage causing water stagnation',
            description: 'The street drainage near our building is completely blocked. Rainwater has been stagnating for days creating breeding ground for mosquitoes. Several residents have reported dengue symptoms.',
            category: 'Sanitation',
            imageUrl: null,
            latitude: 18.5298,
            longitude: 73.8545,
            address: '67 Residency Road, near Medical Store',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 13,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },

        // Electrical - 5 issues (status: 2 received, 2 in_progress, 1 resolved)
        {
            userId: 6,
            title: 'Broken streetlight on Station Road',
            description: 'The streetlight pole number SL-234 on Station Road has been broken for over a month. The area becomes completely dark at night posing safety risks for pedestrians and vehicles.',
            category: 'Electrical',
            imageUrl: null,
            latitude: 18.5456,
            longitude: 73.8767,
            address: 'Station Road, near Auto Stand',
            status: 'in_progress',
            departmentId: 3,
            assignedBy: 1,
            adminNotes: 'New streetlight pole ordered. Installation scheduled for next week.',
            voteCount: 23,
            createdAt: new Date('2024-01-07').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 11,
            title: 'Multiple streetlights not working on College Road',
            description: 'Six consecutive streetlights on College Road have stopped working. The entire stretch is in darkness making it unsafe for students returning from evening classes. This has also increased incidents of chain snatching.',
            category: 'Electrical',
            imageUrl: null,
            latitude: 18.5367,
            longitude: 73.8634,
            address: 'College Road, opposite Engineering College',
            status: 'resolved',
            departmentId: 3,
            assignedBy: 2,
            adminNotes: 'Underground cable fault identified and repaired. All streetlights restored to working condition.',
            voteCount: 24,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            userId: 8,
            title: 'Power cable hanging dangerously low',
            description: 'An overhead power cable is hanging dangerously low on Temple Street after recent storm. It is almost touching tall vehicles and poses serious electrocution risk. Immediate attention required.',
            category: 'Electrical',
            imageUrl: null,
            latitude: 18.5223,
            longitude: 73.8489,
            address: 'Temple Street, near Ganesh Temple',
            status: 'in_progress',
            departmentId: 3,
            assignedBy: 1,
            adminNotes: 'Emergency team dispatched. Cable will be secured and raised to safe height today.',
            voteCount: 20,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            userId: 10,
            title: 'Transformer leaking oil near residential area',
            description: 'The electrical transformer on Gandhi Chowk is leaking oil and making loud humming noises. Residents are concerned about potential fire hazard and health risks from the oil seepage.',
            category: 'Electrical',
            imageUrl: null,
            latitude: 18.5401,
            longitude: 73.8701,
            address: 'Gandhi Chowk, near Community Hall',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 9,
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
        {
            userId: 3,
            title: 'Streetlight causing light pollution in residential area',
            description: 'A newly installed high-intensity streetlight is directly facing bedroom windows of residential buildings. The excessive brightness is disturbing sleep of residents and causing light pollution.',
            category: 'Electrical',
            imageUrl: null,
            latitude: 18.5189,
            longitude: 73.8556,
            address: 'Laxmi Nagar, Sector 7',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 7,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },

        // Water Supply - 5 issues (status: 1 received, 2 in_progress, 1 resolved, 1 rejected)
        {
            userId: 12,
            title: 'Water leakage near Bus Stand',
            description: 'There is a major water leakage from the main pipeline near the bus stand. Thousands of liters of water are being wasted daily and the road has become waterlogged causing traffic problems.',
            category: 'Water Supply',
            imageUrl: null,
            latitude: 18.5478,
            longitude: 73.8745,
            address: 'Central Bus Stand, Platform Area',
            status: 'in_progress',
            departmentId: 4,
            assignedBy: 2,
            adminNotes: 'Pipeline repair work in progress. Water supply temporarily diverted through alternate line.',
            voteCount: 22,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 5,
            title: 'No water supply for 2 days in entire colony',
            description: 'Our entire colony has not received any water supply for the past two days. No prior notice was given and there is no information about when supply will resume. Residents are facing severe hardship.',
            category: 'Water Supply',
            imageUrl: null,
            latitude: 18.5312,
            longitude: 73.8578,
            address: 'Sunrise Colony, Phase 2',
            status: 'resolved',
            departmentId: 4,
            assignedBy: 1,
            adminNotes: 'Pump motor failure was the cause. Motor repaired and water supply restored. Apologies for the inconvenience.',
            voteCount: 25,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 9,
            title: 'Broken water pipeline flooding street',
            description: 'A major water pipeline has burst on Hill Road causing severe flooding. Water is entering ground floor homes and shops. The entire street is submerged under 2 feet of water.',
            category: 'Water Supply',
            imageUrl: null,
            latitude: 18.5534,
            longitude: 73.8812,
            address: 'Hill Road, near Hilltop Apartments',
            status: 'in_progress',
            departmentId: 4,
            assignedBy: 2,
            adminNotes: 'Emergency repair team on site. Main valve closed to stop water flow. Repairs expected to complete by evening.',
            voteCount: 21,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 7,
            title: 'Low water pressure in high-rise buildings',
            description: 'Residents of floors above 5th floor in multiple buildings are experiencing very low water pressure for the past week. Water barely reaches upper floors during peak hours making daily activities difficult.',
            category: 'Water Supply',
            imageUrl: null,
            latitude: 18.5256,
            longitude: 73.8501,
            address: 'Sky View Towers, Sector 15',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 10,
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            userId: 4,
            title: 'Dirty and contaminated water supply',
            description: 'The water coming from taps has been yellowish in color for the past three days. It has a strange odor and visible particles. We suspect contamination and are concerned about health risks.',
            category: 'Water Supply',
            imageUrl: null,
            latitude: 18.5423,
            longitude: 73.8689,
            address: 'Pearl Society, Block B',
            status: 'rejected',
            departmentId: 4,
            assignedBy: 1,
            adminNotes: 'Water quality tests conducted. No contamination found. Discoloration was due to maintenance work in society\'s internal tank. Issue is with building maintenance, not municipal supply.',
            voteCount: 6,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },

        // Waste Management - 4 issues (status: 1 received, 1 in_progress, 1 resolved, 1 rejected)
        {
            userId: 11,
            title: 'Illegal dumping site near school',
            description: 'An illegal waste dumping site has emerged on vacant land near the primary school. People are dumping construction waste, household garbage, and even hazardous materials. This poses serious health risk to children.',
            category: 'Waste Management',
            imageUrl: null,
            latitude: 18.5345,
            longitude: 73.8612,
            address: 'Empty Plot, near Primary School',
            status: 'in_progress',
            departmentId: 5,
            assignedBy: 1,
            adminNotes: 'Cleanup operation initiated. Waste removal in progress. Land will be fenced and signage installed to prevent future dumping.',
            voteCount: 19,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: 6,
            title: 'Plastic waste accumulation near market',
            description: 'Massive amounts of plastic bags and containers have accumulated near the vegetable market. The wind is spreading this plastic waste across residential areas. Proper waste segregation and disposal system needed urgently.',
            category: 'Waste Management',
            imageUrl: null,
            latitude: 18.5201,
            longitude: 73.8534,
            address: 'Vegetable Market, Main Gate Area',
            status: 'resolved',
            departmentId: 5,
            assignedBy: 2,
            adminNotes: 'Plastic waste collected and sent for recycling. Additional waste bins installed at market. Awareness campaign conducted among vendors.',
            voteCount: 15,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 8,
            title: 'Medical waste found in regular garbage',
            description: 'Used syringes, medicine bottles, and other medical waste from nearby clinic are being mixed with regular garbage. This is extremely dangerous and violates waste disposal regulations. Clinic should be penalized.',
            category: 'Waste Management',
            imageUrl: null,
            latitude: 18.5289,
            longitude: 73.8567,
            address: 'Health Clinic, Main Road',
            status: 'rejected',
            departmentId: 5,
            assignedBy: 1,
            adminNotes: 'Investigation conducted. Medical waste was not from the clinic mentioned. The complaint location was incorrect. Issue forwarded to appropriate authorities for source identification.',
            voteCount: 5,
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            userId: 10,
            title: 'No segregation bins for wet and dry waste',
            description: 'Our neighborhood has only single waste collection bins. There are no separate bins for wet and dry waste segregation as per municipal guidelines. This is making it impossible for residents to follow waste segregation rules.',
            category: 'Waste Management',
            imageUrl: null,
            latitude: 18.5412,
            longitude: 73.8723,
            address: 'Garden View Apartments, Block C',
            status: 'received',
            departmentId: null,
            assignedBy: null,
            adminNotes: null,
            voteCount: 8,
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
    ];

    await db.insert(issues).values(sampleIssues);
    
    console.log('✅ Issues seeder completed successfully - 28 realistic civic issues created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});